name: 'Verify Pulumi Provider Release'
description: 'Verifies that a published provider is usable'
author: 'Pulumi'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'check-circle'
  color: 'purple'

# Define your inputs here.
inputs:
  language:
    description:
      The language to test against. One of `nodejs`, `python`, `dotnet`, `go` or
      `java`.
    required: true
  directory:
    description: Path to a Pulumi program to use for the test.
    required: true
  provider:
    description: The name of the provider (excluding the publisher prefix)
    required: true
  providerVersion:
    description: The version of the provider to be tested.
    required: true
  packageVersion:
    description:
      The version of the package to be tested. Defaults to `providerVersion` if
      not set.
  publisher:
    description: The publisher of the provider (if not pulumi)
    default: pulumi
  goModuleTemplate:
    description: |
      Template to generate the go module to be used.
      Available template fields: `{publisher}`, `{provider}`, `{moduleVersionSuffix}`
      {moduleVersionSuffix} is calculated from the provider version e.g. "/v2"
    default: github.com/{publisher}/pulumi-{provider}/sdk{moduleVersionSuffix}

# Define your outputs here.
outputs: {}

runs:
  using: node20
  main: dist/index.js
